version: '2.1'

services:
  client:
   build:
     context: ./client
     dockerfile: Dockerfile
   volumes:
    - web-data:/home/app/code/node_modules
    - ./client:/home/app/code
   ports:
    - 3000:3000

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - my-datavolume:/var/lib/mysql

  api:
   build:
     context: ./api
     dockerfile: Dockerfile
   ports:
    - 3001:3001
    - 8000:8000
   depends_on:
    - db
   volumes:
    - api-data:/home/app/code/node_modules

volumes:
  api-data:
  my-datavolume:
  web-data: